---
title: "'Exit Try' só pode aparecer dentro de uma instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: d07afdb2c6026028e765173b87e869aedb0d3155
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53763533"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' só pode aparecer dentro de uma instrução 'Try'
`Exit Try` só pode aparecer dentro de um `Try` bloco de instrução. Ou você tem um redundantes `Exit Try` instrução, ou sua `Exit Try` instrução aparece fora dos limites de seu correspondente `Try` bloco.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1.  Localize e remova o desnecessárias `Exit Try` instrução.  
  
2.  Mover o `Exit Try` instrução até o local apropriado dentro de seu código.  
  
## <a name="see-also"></a>Consulte também  
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
