---
title: "'Exit Try' só pode aparecer dentro de uma instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 53c8ee60907db16ac97147100636e413f1cbc15e
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58043360"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' só pode aparecer dentro de uma instrução 'Try'
`Exit Try` só pode aparecer dentro de um `Try` bloco de instrução. Ou você tem um redundantes `Exit Try` instrução, ou sua `Exit Try` instrução aparece fora dos limites de seu correspondente `Try` bloco.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1.  Localize e remova o desnecessárias `Exit Try` instrução.  
  
2.  Mover o `Exit Try` instrução até o local apropriado dentro de seu código.  
  
## <a name="see-also"></a>Consulte também

- [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
