---
title: O operando &quot;Throw&quot; deve derivar de &quot;System. Exception&quot; | Documentos do Microsoft
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
caps.latest.revision: 9
author: dotnet-bot
ms.author: dotnetcontent
translation.priority.ht:
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- ru-ru
- zh-cn
- zh-tw
translation.priority.mt:
- cs-cz
- pl-pl
- pt-br
- tr-tr
translationtype: Machine Translation
ms.sourcegitcommit: a06bd2a17f1d6c7308fa6337c866c1ca2e7281c0
ms.openlocfilehash: fef46f61869564e0b483efa53ca94ebb4f3d43f7
ms.lasthandoff: 03/13/2017

---
# <a name="39throw39-operand-must-derive-from-39systemexception39"></a>O operando 'Throw' deve derivar de 'System. Exception'
O argumento fornecido para `Throw` deve ser uma instância de `System.Exception` ou uma instância de uma classe derivada de `System.Exception`.  
  
 **ID do erro:** BC30665  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
-   Use um argumento derivado de `System.Exception`, como no exemplo a seguir.  
  
    ```  
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>Consulte também  
 [Instrução throw](../../visual-basic/language-reference/statements/throw-statement.md)   
 [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)   
 [Classe de exceção no Visual Basic](http://msdn.microsoft.com/en-us/9aac396f-34ca-4afb-8e6c-e523cb690ba9)   
 [Exceção e tratamento de erros no Visual Basic](http://msdn.microsoft.com/en-us/3e351e73-cf23-40ab-8b60-05794160529e)
