---
title: "'Exit Try' só pode aparecer dentro de uma instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 7e7d1a1a9025c2d708d7e5027fd9bcbb4270e60b
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/18/2019
ms.locfileid: "59320399"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' só pode aparecer dentro de uma instrução 'Try'
`Exit Try` só pode aparecer dentro de um `Try` bloco de instrução. Ou você tem um redundantes `Exit Try` instrução, ou sua `Exit Try` instrução aparece fora dos limites de seu correspondente `Try` bloco.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Localize e remova o desnecessárias `Exit Try` instrução.  
  
2. Mover o `Exit Try` instrução até o local apropriado dentro de seu código.  
  
## <a name="see-also"></a>Consulte também

- [Instrução Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
