---
title: "Como manipular uma exceção usando try-catch (Guia de programação em C#)"
ms.date: 2015-07-20
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
dev_langs:
- CSharp
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
caps.latest.revision: 14
author: BillWagner
ms.author: wiwagn
translation.priority.ht:
- cs-cz
- de-de
- es-es
- fr-fr
- it-it
- ja-jp
- ko-kr
- pl-pl
- pt-br
- ru-ru
- tr-tr
- zh-cn
- zh-tw
ms.translationtype: HT
ms.sourcegitcommit: 306c608dc7f97594ef6f72ae0f5aaba596c936e1
ms.openlocfilehash: f6f714cd1b652845e77405ff74fbfc860e71dc21
ms.contentlocale: pt-br
ms.lasthandoff: 07/28/2017

---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="06c6f-102">Como manipular uma exceção usando try/catch (Guia de Programação em C#)</span><span class="sxs-lookup"><span data-stu-id="06c6f-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="06c6f-103">A finalidade de um bloco [try-catch](../../../csharp/language-reference/keywords/try-catch.md) é capturar e manipular uma exceção gerada pelo código de trabalho.</span><span class="sxs-lookup"><span data-stu-id="06c6f-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="06c6f-104">Algumas exceções podem ser manipuladas em um bloco `catch` e o problema pode ser resolvido sem que a exceção seja gerada novamente. No entanto, com mais frequência, a única coisa que você pode fazer é certificar-se de que a exceção apropriada seja gerada.</span><span class="sxs-lookup"><span data-stu-id="06c6f-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="06c6f-105">Exemplo</span><span class="sxs-lookup"><span data-stu-id="06c6f-105">Example</span></span>  
 <span data-ttu-id="06c6f-106">Neste exemplo, <xref:System.IndexOutOfRangeException> não é a exceção mais apropriada: <xref:System.ArgumentOutOfRangeException> faz mais sentido para o método porque o erro é causado pelo argumento `index` passado pelo chamador.</span><span class="sxs-lookup"><span data-stu-id="06c6f-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 <span data-ttu-id="06c6f-107">[!code-cs[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]</span><span class="sxs-lookup"><span data-stu-id="06c6f-107">[!code-cs[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]</span></span>  
  
## <a name="comments"></a><span data-ttu-id="06c6f-108">Comentários</span><span class="sxs-lookup"><span data-stu-id="06c6f-108">Comments</span></span>  
 <span data-ttu-id="06c6f-109">O código que causa uma exceção fica dentro do bloco `try`.</span><span class="sxs-lookup"><span data-stu-id="06c6f-109">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="06c6f-110">A instrução `catch` é adicionada logo após para manipular `IndexOutOfRangeException`, se ocorrer.</span><span class="sxs-lookup"><span data-stu-id="06c6f-110">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="06c6f-111">O bloco `catch` manipula o `IndexOutOfRangeException` e gera a exceção `ArgumentOutOfRangeException`, que é mais adequada.</span><span class="sxs-lookup"><span data-stu-id="06c6f-111">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="06c6f-112">Para fornecer ao chamador tantas informações quanto possível, considere especificar a exceção original como o <xref:System.Exception.InnerException%2A> da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="06c6f-112">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="06c6f-113">Uma vez que a propriedade <xref:System.Exception.InnerException%2A> é [readonly](../../../csharp/language-reference/keywords/readonly.md), você precisa atribuí-la no construtor da nova exceção.</span><span class="sxs-lookup"><span data-stu-id="06c6f-113">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="06c6f-114">Consulte também</span><span class="sxs-lookup"><span data-stu-id="06c6f-114">See Also</span></span>  
 <span data-ttu-id="06c6f-115">[Guia de Programação em C#](../../../csharp/programming-guide/index.md) </span><span class="sxs-lookup"><span data-stu-id="06c6f-115">[C# Programming Guide](../../../csharp/programming-guide/index.md) </span></span>  
 <span data-ttu-id="06c6f-116">[Exceções e tratamento de exceções](../../../csharp/programming-guide/exceptions/index.md) </span><span class="sxs-lookup"><span data-stu-id="06c6f-116">[Exceptions and Exception Handling](../../../csharp/programming-guide/exceptions/index.md) </span></span>  
 [<span data-ttu-id="06c6f-117">Tratamento de Exceção</span><span class="sxs-lookup"><span data-stu-id="06c6f-117">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)

